# Generated by Django 3.1.3 on 2020-12-07 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_id', models.PositiveIntegerField(unique=True)),
                ('screen_name', models.CharField(max_length=16)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256, null=True)),
                ('url', models.URLField(null=True)),
                ('description', models.CharField(max_length=512, null=True)),
                ('created_at', models.DateTimeField()),
                ('statuses_count', models.PositiveIntegerField()),
                ('followers_count', models.PositiveIntegerField()),
                ('friends_count', models.PositiveIntegerField()),
                ('listed_count', models.PositiveIntegerField()),
                ('default_profile', models.BooleanField()),
                ('verified', models.BooleanField()),
                ('protected', models.BooleanField()),
                ('bot_score', models.FloatField()),
                ('is_active', models.BooleanField()),
                ('date_of_snapshot', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
    ]
