# Generated by Django 3.1.3 on 2020-12-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsnapshot',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='accountsnapshot',
            name='location',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='accountsnapshot',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
