# Generated by Django 3.1.3 on 2020-12-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201207_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsnapshot',
            name='favourites_count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
