# Generated by Django 3.1.3 on 2020-12-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_accountsnapshot_favourites_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsnapshot',
            name='screen_name',
        ),
        migrations.AlterField(
            model_name='account',
            name='screen_name',
            field=models.CharField(max_length=128),
        ),
    ]
