# Generated by Django 3.1.3 on 2020-12-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201210_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsnapshot',
            name='suspended_info',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
