# Generated by Django 3.1.3 on 2020-12-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_accountsnapshot_suspended_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsnapshot',
            name='suspended_info',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
